In [32]:
# importing packages


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import confusion_matrix , accuracy_score
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier , KNeighborsRegressor
from sklearn.impute import SimpleImputer



In [12]:
# importing dataset

from sklearn import datasets
from sklearn.datasets import load_digits

In [13]:
print(dir(datasets))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_arff_parser', '_base', '_california_housing', '_covtype', '_kddcup99', '_lfw', '_olivetti_faces', '_openml', '_rcv1', '_samples_generator', '_species_distributions', '_svmlight_format_fast', '_svmlight_format_io', '_twenty_newsgroups', 'clear_data_home', 'data', 'descr', 'dump_svmlight_file', 'fetch_20newsgroups', 'fetch_20newsgroups_vectorized', 'fetch_california_housing', 'fetch_covtype', 'fetch_kddcup99', 'fetch_lfw_pairs', 'fetch_lfw_people', 'fetch_olivetti_faces', 'fetch_openml', 'fetch_rcv1', 'fetch_species_distributions', 'get_data_home', 'load_breast_cancer', 'load_diabetes', 'load_digits', 'load_files', 'load_iris', 'load_linnerud', 'load_sample_image', 'load_sample_images', 'load_svmlight_file', 'load_svmlight_files', 'load_wine', 'make_biclusters', 'make_blobs', 'make_checkerboard', 'make_circles', 'make_classification', 'make_fr

In [11]:
mnist  = load_digits()

In [16]:
dir(mnist)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [19]:
mnist.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [22]:
print("number of rows : ",mnist.data.shape[0])
print("number of columns : ",mnist.data.shape[1])

number of rows :  1797
number of columns :  64


In [28]:
X  = mnist['data']
y = mnist['target']

In [29]:
# Train Test Split

X_train , X_test , y_train , y_test = train_test_split(X,y , test_size= 0.2 , random_state= 123)

In [33]:
# model Building

model = KNeighborsClassifier().fit(X_train , y_train)

In [34]:
train_pred =  model.predict(X_train)
test_pred = model.predict(X_test)

In [35]:
print("Accuracy Score  : " , accuracy_score(y_train , train_pred))
print("Accuracy Score  : " , accuracy_score(y_test , test_pred))

Accuracy Score  :  0.9902574808629089
Accuracy Score  :  0.9805555555555555


In [41]:
print("Confusion Matrix for Train Predictions : \n\n" , confusion_matrix(y_train , train_pred))
print('\n')
print("Confusion Matrix for Test Predictions : \n\n" , confusion_matrix(y_test , test_pred))


Confusion Matrix for Train Predictions : 

 [[139   0   0   0   0   0   0   0   0   0]
 [  0 148   0   0   0   0   0   0   0   0]
 [  0   0 141   0   0   0   0   0   0   0]
 [  0   0   0 148   0   0   0   2   0   0]
 [  0   0   0   0 139   0   0   0   0   0]
 [  0   0   0   0   0 143   1   0   0   1]
 [  0   0   0   0   0   0 137   0   1   0]
 [  0   0   0   0   0   0   0 147   0   1]
 [  0   2   0   1   0   0   0   0 134   0]
 [  0   1   0   1   1   1   0   0   1 147]]


Confusion Matrix for Test Predictions : 

 [[39  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0]
 [ 0  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  0]
 [ 0  0  0  0 41  0  0  1  0  0]
 [ 0  0  0  0  0 36  0  0  0  1]
 [ 0  0  0  0  0  0 43  0  0  0]
 [ 0  0  0  0  0  0  0 31  0  0]
 [ 0  3  1  0  0  0  0  0 33  0]
 [ 0  0  0  1  0  0  0  0  0 27]]


In [51]:
print('Number of incorrect predcitions on train data :', len(train_pred[train_pred!=y_train]))

Number of incorrect predcitions on train data : 14


In [50]:
print('Number of incorrect predcitions on test data :' , len(test_pred[test_pred!=y_test]))

Number of incorrect predcitions on test data : 7
